version: "3.8"

services:
  accounts:
    image: naveejr/accounts:latest
    mem_limit: 700m
    ports:
      - "8080:8080"
    networks:
      - microbank-network
  loans:
    image: naveejr/loans:latest
    mem_limit: 700m
    ports:
      - "8090:8090"
    networks:
      - microbank-network

  cards:
    image: naveejr/cards:latest
    mem_limit: 700m
    ports:
      - "9000:9000"
    networks:
      - microbank-network

networks:
  microbank-network:
