version: "3.8"

services:

  grafana:
    image: "grafana/grafana:latest"
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=password
    networks:
     - microbank-network
    depends_on:
      - prometheus  
  prometheus:
   image: prom/prometheus:latest
   ports:
      - "9090:9090"
   volumes:
    - ./prometheus.yml:/etc/prometheus/prometheus.yml
   networks:
    - microbank-network
    
  zipkinserver:
    image: openzipkin/zipkin
    mem_limit: 700m
    ports:
      - "9411:9411"
    networks:
     - microbank-network  

  configserver:
    image: naveejr/config-server:latest
    mem_limit: 700m
    ports:
      - "8071:8071"
    depends_on:
      - zipkinserver
    networks:
     - microbank-network
    environment:
      SPRING_ZIPKIN_BASEURL: http://zipkinserver:9411/
      
  eurekaserver:
    image: naveejr/eureka-server:latest
    mem_limit: 700m
    ports:
      - "8070:8070"
    networks:
     - microbank-network
    depends_on:
      - configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      SPRING_ZIPKIN_BASEURL: http://zipkinserver:9411/
      
  accounts:
    image: naveejr/accounts:latest
    mem_limit: 700m
    ports:
      - "8080:8080"
    networks:
      - microbank-network
    depends_on:
      - configserver
      - eurekaserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
      SPRING_ZIPKIN_BASEURL: http://zipkinserver:9411/
  
  loans:
    image: naveejr/loans:latest
    mem_limit: 700m
    ports:
      - "8090:8090"
    networks:
      - microbank-network
    depends_on:
      - configserver
      - eurekaserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
      SPRING_ZIPKIN_BASEURL: http://zipkinserver:9411/
    
  cards:
    image: naveejr/cards:latest
    mem_limit: 700m
    ports:
      - "9000:9000"
    networks:
      - microbank-network
    depends_on:
      - configserver
      - eurekaserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
      SPRING_ZIPKIN_BASEURL: http://zipkinserver:9411/
   
  gatewayserver:
    image: naveejr/gateway-server:latest
    mem_limit: 700m
    ports:
      - "8072:8072"
    networks:
      - microbank-network
    depends_on:
      - configserver
      - eurekaserver
      - cards
      - loans
      - accounts
    deploy:
      restart_policy:
        condition: on-failure
        delay: 45s
        max_attempts: 3
        window: 180s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
      SPRING_ZIPKIN_BASEURL: http://zipkinserver:9411/
      
networks:
  microbank-network:
